stages:
  load_data:
    cmd: python mlops/load_data.py data/raw/heart_failure_clinical_records_dataset.csv data/processed/train_test_data.csv
    deps:
    - mlops/load_data.py
    - data/raw/heart_failure_clinical_records_dataset.csv
    outs:
    - data/processed/train_test_data.csv
      
  preprocess:
    cmd: python mlops/preprocess.py data/processed/train_test_data.csv data/processed/X_train.csv data/processed/X_test.csv data/processed/y_train.csv data/processed/y_test.csv
    deps:
      - mlops/preprocess.py
      - data/processed/train_test_data.csv
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  run_experiment_rf:
    cmd: python mlops/model_tracking/run_experiment.py --model_type random_forest --x_train_path data/processed/X_train.csv --y_train_path data/processed/y_train.csv --x_test_path data/processed/X_test.csv --y_test_path data/processed/y_test.csv --params_path params/random_forest.yaml --model_path models/model_rf.pkl
    deps:
      - params/random_forest.yaml
      - mlops/model_tracking
      - data/processed/X_train.csv
      - data/processed/y_train.csv
      - data/processed/X_test.csv
      - data/processed/y_test.csv
    outs:
      - models/model_rf.pkl

  run_experiment_rf_cv:
    cmd: python mlops/model_tracking/run_experiment.py --model_type random_forest --x_train_path data/processed/X_train.csv --y_train_path data/processed/y_train.csv --x_test_path data/processed/X_test.csv --y_test_path data/processed/y_test.csv --params_path params/random_forest_cv.yaml --model_path models/model_rf_cv.pkl --use_cv
    deps:
      - params/random_forest_cv.yaml
      - mlops/model_tracking
      - data/processed/X_train.csv
      - data/processed/y_train.csv
      - data/processed/X_test.csv
      - data/processed/y_test.csv
    outs:
      - models/model_rf_cv.pkl

  run_experiment_dt:
    cmd: python mlops/model_tracking/run_experiment.py --model_type decision_tree --x_train_path data/processed/X_train.csv --y_train_path data/processed/y_train.csv --x_test_path data/processed/X_test.csv --y_test_path data/processed/y_test.csv --params_path params/decision_tree.yaml --model_path models/model_rf.pkl
    deps:
      - params/decision_tree.yaml
      - mlops/model_tracking
      - data/processed/X_train.csv
      - data/processed/y_train.csv
      - data/processed/X_test.csv
      - data/processed/y_test.csv
    outs:
      - models/model_rf.pkl

  run_experiment_dt_cv:
    cmd: python mlops/model_tracking/run_experiment.py --model_type decision_tree --x_train_path data/processed/X_train.csv --y_train_path data/processed/y_train.csv --x_test_path data/processed/X_test.csv --y_test_path data/processed/y_test.csv --params_path params/decision_tree_cv.yaml --model_path models/model_rf_cv.pkl --use_cv
    deps:
      - params/decision_tree_cv.yaml
      - mlops/model_tracking
      - data/processed/X_train.csv
      - data/processed/y_train.csv
      - data/processed/X_test.csv
      - data/processed/y_test.csv
    outs:
      - models/model_rf_cv.pkl