stages:
  load_data:
    cmd: python mlops/load_data.py data/external/heart_failure_clinical_records_dataset.csv data/processed/train_test_data.csv
    deps:
    - mlops/load_data.py
    - data/external/heart_failure_clinical_records_dataset.csv
    outs:
    - data/processed/train_test_data.csv
      
  preprocess:
    cmd: python mlops/preprocess.py data/processed/train_test_data.csv data/processed/X_train.csv data/processed/X_test.csv data/processed/y_train.csv data/processed/y_test.csv
    deps:
      - mlops/preprocess.py
      - data/processed/train_test_data.csv
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  train:
    cmd: python mlops/train_rf.py data/processed/X_train.csv data/processed/y_train.csv models/model_rf.pkl
    deps:
      - mlops/train_rf.py
      - data/processed/X_train.csv
      - data/processed/y_train.csv
    outs:
        - models/model_rf.pkl

  evaluate:
    cmd: python mlops/evaluate.py models/model_rf.pkl data/processed/X_test.csv data/processed/y_test.csv
    deps:
      - mlops/evaluate.py
      - data/processed/X_test.csv
      - data/processed/y_test.csv
      - models/model_rf.pkl