stages:
  load_data:
    cmd: python -m mlops.load_data data/raw/heart_failure_clinical_records_dataset.csv data/processed/train_test_data.csv
    deps:
    - mlops/load_data.py
    - data/raw/heart_failure_clinical_records_dataset.csv
    outs:
    - data/processed/train_test_data.csv
      
  split_data:
    cmd: python -m mlops.split data/processed/train_test_data.csv data/processed/X_train.csv data/processed/X_test.csv data/processed/y_train.csv data/processed/y_test.csv
    deps:
      - mlops/split.py
      - data/processed/train_test_data.csv
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  create_preprocessor:
    cmd: python -m mlops.create_preprocessor --x_train_path data/processed/X_train.csv --preprocessor_path models/preprocessor.pkl
    deps:
      - mlops/create_preprocessor.py
      - data/processed/X_train.csv
    outs:
      - models/preprocessor.pkl

  run_experiment_rf:
    cmd: python -m mlops.model_tracking.run_experiment --model_type random_forest --x_train_path data/processed/X_train.csv --y_train_path data/processed/y_train.csv --x_test_path data/processed/X_test.csv --y_test_path data/processed/y_test.csv --preprocessor_path models/preprocessor.pkl --params_path params/random_forest.yaml --model_path models/model_rf.pkl
    deps:
      - models/preprocessor.pkl
      - params/random_forest.yaml
      - mlops/model_tracking
      - data/processed/X_train.csv
      - data/processed/y_train.csv
      - data/processed/X_test.csv
      - data/processed/y_test.csv
    outs:
      - models/model_rf.pkl

  run_experiment_rf_cv:
    cmd: python -m mlops.model_tracking.run_experiment --model_type random_forest --x_train_path data/processed/X_train.csv --y_train_path data/processed/y_train.csv --x_test_path data/processed/X_test.csv --y_test_path data/processed/y_test.csv --preprocessor_path models/preprocessor.pkl --params_path params/random_forest_cv.yaml --model_path models/model_rf_cv.pkl --use_cv
    deps:
      - models/preprocessor.pkl
      - params/random_forest_cv.yaml
      - mlops/model_tracking
      - data/processed/X_train.csv
      - data/processed/y_train.csv
      - data/processed/X_test.csv
      - data/processed/y_test.csv
    outs:
      - models/model_rf_cv.pkl

  run_experiment_dt:
    cmd: python -m mlops.model_tracking.run_experiment --model_type decision_tree --x_train_path data/processed/X_train.csv --y_train_path data/processed/y_train.csv --x_test_path data/processed/X_test.csv --y_test_path data/processed/y_test.csv --preprocessor_path models/preprocessor.pkl --params_path params/decision_tree.yaml --model_path models/model_dt.pkl
    deps:
      - models/preprocessor.pkl
      - params/decision_tree.yaml
      - mlops/model_tracking
      - data/processed/X_train.csv
      - data/processed/y_train.csv
      - data/processed/X_test.csv
      - data/processed/y_test.csv
    outs:
      - models/model_dt.pkl

  run_experiment_dt_cv:
    cmd: python -m mlops.model_tracking.run_experiment --model_type decision_tree --x_train_path data/processed/X_train.csv --y_train_path data/processed/y_train.csv --x_test_path data/processed/X_test.csv --y_test_path data/processed/y_test.csv --preprocessor_path models/preprocessor.pkl --params_path params/decision_tree_cv.yaml --model_path models/model_dt_cv.pkl --use_cv
    deps:
      - models/preprocessor.pkl
      - params/decision_tree_cv.yaml
      - mlops/model_tracking
      - data/processed/X_train.csv
      - data/processed/y_train.csv
      - data/processed/X_test.csv
      - data/processed/y_test.csv
    outs:
      - models/model_dt_cv.pkl